default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: ror_url_shortener_development

test:
  <<: *default
  database: ror_url_shortener_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %> 
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
